name: Run Unit Tests

on: [push, pull_request]

jobs: 
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          persist-credentials: true # Assure que les credentials sont disponibles pour push

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        id: test
        run: npm test

      - name: Ensure test-results directory exists
        run: mkdir -p test-results

      - name: Upload test results
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results
          if-no-files-found: ignore

      - name: Create test status badge
        run: |
          if [ "${{ steps.test.outcome }}" == "success" ]; then
            echo "![Tests](https://img.shields.io/badge/tests-passing-brightgreen)" > test-status.md
          else
            echo "![Tests](https://img.shields.io/badge/tests-failing-red)" > test-status.md
          fi

      - name: Commit and push test status
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add test-status.md
          git commit -m "Update test status badge"
          git push
