name: Run Unit Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        id: test
        run: npm test

      - name: Upload test results
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results

      - name: Create test status badge
        run: |
          if [ ${{ steps.test.outcome }} == 'success' ]; then
            echo "![Tests](https://img.shields.io/badge/tests-passing-brightgreen)" > test-status.md
          else
            echo "![Tests](https://img.shields.io/badge/tests-failing-red)" > test-status.md
          fi

      - name: Upload test status badge
        uses: actions/upload-artifact@v4
        with:
          name: test-status
          path: test-status.md

      - name: Update README with badge
        run: |
          # Download the badge artifact
          curl -L -o test-status.md ${{ steps.upload-badge.outputs.artifact-url }}

          # Replace the badge in README.md
          sed -i '/!\[Tests\].*/d' README.md
          cat test-status.md >> README.md

          # Commit and push the changes
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "Update test status badge in README"
          git push